### ISSUE TITLE
Assign the test resources process some other name to distinguish between the Application and the TR

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#116]
### Issue description

The current behavior is two processes `Application`:
```
> jps
1808 
82723 Application
82707 GradleDaemon
82724 Application
96009 
82729 Jps
```

**Comment by melix** [comment]
I agree that it was an unfortunate decision to keep the default `Application` name. Changing it is easy in `micronaut-test-resources`, but it is a breaking change, as it will break integration with build tools:

- previous releases of build tools wouldn't be able to use newer releases of `test-resources` (because they would start the process with `Application` instead of the new name)
- newer releases wouldn't be able to use older releases of `test-resources` (less likely of a problem)

So maybe target that change for Micronaut 4/Micronaut Test Resources 2.0
