### ISSUE TITLE
Missing property is crashing bean context initialization

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#129]
### Expected Behavior

Not crashing

### Actual Behaviour

`Optional<String> resolve` in the controller will produce 404 on missing value, which will fail with an exception during the client fetch.

Example: 
[data-r2dbc.zip](https://github.com/micronaut-projects/micronaut-test-resources/files/10073281/data-r2dbc.zip)

### Version

3.6.5

**Comment by dstepanov** [comment]
The project can be fixed by adding:
```
      schema-generate: CREATE_DROP
      dialect: POSTGRES
 ```
 To the R2DBC config.

**Comment by melix** [comment]
There are a couple of problems:

- in your project, the cause is the wrong `db-type` in `application.yml`, which should be `postgres`, not `postgresql`. I can make the resolver leaner by supporting both. When you add `dialect`, the resolver recognizes it should answer.
- in test resources, you can have several resolvers capable of answering, so we iterate on each of them until one answers. In this case, none of the resolvers was able to answer, so we return an empty optional.

I don't think this issue can be easily solved, because of the underlying architecture in Micronaut. Basically we have property resolvers, and property resolvers must be able to tell what properties they can answer, solely based on the _keys_ of other properties in configuration. In this case, we say that we can resolve `r2dbc.datasources.default.url`. At this stage, we _cannot_ know if the properties we need for resolution are going to be available or not, but we _assume_ they will. This works well in general, but in this case, the resolver expects at least one of the hints to be available, either the db-type, the dialect, etc. Since it finds none, it answers "nope, sorry I cannot tell you the value, try with the next resolver". But we're going to exhaust all resolvers, so the answer is going to be empty. We then have a mismatch between what core wanted, that is to say a resolver which returns something, and what we can return...

**Comment by melix** [comment]
Possibility: Instead of returning an empty optional in the controller, we could instead throw an exception, because it would mean a resolver said it could resolve a property, but none did. This would cause an error message to be visible in the build logs, but it wouldn't change the error on the client side (the one reported at startup).

**Comment by dstepanov** [comment]
The main problem here is that the HTTP client is not going to return `Optional` but the exception:

```java
    @Post("/resolve")
    public Optional<String> resolve(String name,
                                    Map<String, Object> properties,
                                    Map<String, Object> testResourcesConfig) {
        Optional<String> result = Optional.empty();
        for (TestResourcesResolver resolver : loader.getResolvers()) {
            result = resolver.resolve(name, properties, testResourcesConfig);
            LOGGER.debug("Attempt to resolve {} with resolver {}, properties {} and test resources configuration {} : {}", name, resolver.getClass(), properties, testResourcesConfig, result.isPresent() ? result.get() : "\uD83D\uDEAB");
            if (result.isPresent()) { // Never going to happened as the exception is thrown in this case
                return result;
            }
        }
        return result;
    }
```

**Comment by melix** [comment]
I don't understand what you mean: the issue happens because we reach the last `return result`, where the result is `Optional#empty()`. Then the client sees an empty result, but the resolver wanted a value (that's the contract of `PropertyExpressionResolver`), so it ends up blowing up.

If I replace the `return result` with throwing an exception, then we see an exception in the logs, that it couldn't resolve the property. For example, I can throw:

> Could not resolve property r2dbc.datasources.default.url

which would appear in the console. But it doesn't change anything for the resolver, which would still fail, because at this stage, we said "I, property expression resolver, will resolve this property".

**Comment by dstepanov** [comment]
Ahh sorry for the confusion, I posted the wrong code (instead of the client code I posted the controller):

```java
private static class DelegateResolver implements PropertyExpressionResolver, AutoCloseable {
        private final Map<Environment, TestResourcesClient> clients = new ConcurrentHashMap<>();

        @Override
        public <T> Optional<T> resolve(PropertyResolver propertyResolver,
                                       ConversionService<?> conversionService,
                                       String expression,
                                       Class<T> requiredType) {
            if (propertyResolver instanceof Environment) {
                TestResourcesClient client = clients.computeIfAbsent((Environment) propertyResolver, TestResourcesClientPropertyExpressionResolver::createClient);
                Map<String, Object> props = resolveRequiredProperties(expression, propertyResolver, client);
                Map<String, Object> properties = propertyResolver.getProperties(TestResourcesResolver.TEST_RESOURCES_PROPERTY);
                Optional<String> resolved = client.resolve(expression, props, properties);
                /// HERE is never going to be an unresolved property as it will be 404 exception in this case
                if (resolved.isPresent()) {
                    String resolvedValue = resolved.get();
                    LOGGER.debug("Resolved expression '{}' to '{}'", expression, resolvedValue);
                    return conversionService.convert(resolvedValue, requiredType);
                } else if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("Test resources cannot resolve expression '{}'", expression);
                }
            }
            return Optional.empty();
        }
 ```
