### ISSUE TITLE
Support configuring Hibernate reactive

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#15]
### Feature description

Micronaut SQL is not released yet but it brings support for Hibernate Reactive https://micronaut-projects.github.io/micronaut-sql/snapshot/guide/index.html

See examples https://github.com/micronaut-projects/micronaut-sql/tree/master/tests/hibernate5

**Comment by melix** [comment]
That's an interesting use case. So if I understand properly, depending on what dependencies you add, there properties to be filled will be different. Either `jpa.*.properties.hibernate.connection.url` (etc), or `vertx.[db-id].client.host` (etc).

Let me know when a release is available so that I see how to add support.

**Comment by dstepanov** [comment]
Yes, but I would ignore the second case, for now, we only support two databases and there is no way to define multiple configurations.

**Comment by dstepanov** [comment]
There is a new Micronaut SQL release v4.5.0 that includes it
