### ISSUE TITLE
Data inserted in test container database not available to service class when hitting endpoint using http client

### ISSUE THREAD

**Issue by ashwan1** [micronaut-projects/micronaut-test-resources#157]
### Expected Behavior

**Given:**
- we are using testcontainers (micronaut-test-resources)
- we insert some dummy data in table in test class

**When:**
- we hit controller endpoint using HTTP client

**Then:**
- Inserted data should be available to controller class

### Actual Behaviour

**Given:**
- we are using testcontainers (micronaut-test-resources)
- we insert some dummy data in table in test class

**When:**
- we hit controller endpoint using HTTP client

**Then:**
- Inserted data is not available to controller class and therefore test case fails

### Steps To Reproduce

1. Create a controller which reads data from database
2. Create a test case, in which insert dummy data in table using micronaut-data-jdbc
3. Use HTTP client to hit controller endpoint from test case

### Environment Information

- GraalVM 
- Java 17

### Example Application

[Git repo to replicate this issue](https://github.com/ashwan1/demo.git)

### Version

3.8.0

**Comment by ashwan1** [comment]
@melix I have updated my issue with the link to the GitHub repo. Please run test case to replicate the issue.

**Comment by melix** [comment]
Right, if I switch to Postgres in your example I can reproduce, but I don't think it's an issue with test resources. It's because by default `@MicronautTest` has `transactional=true`, which means that the repository you get is decorated to handle transactions. If I set it to `false`, then the test passes. See also https://sergiodelamo.com/blog/micronaut-test-transactional-false.html

I am not quite sure how you'd reset the state of the DB after each test method, though, maybe @dstepanov can tell.

**Comment by dstepanov** [comment]
`@MicronautTest` if used with `transactional=true` should rollback the changes by default
