### ISSUE TITLE
Re-enable Hibernate Reactive support

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-test-resources#189]
### Issue description

Once a version of Hibernate Reactive compatible with Hibernate 6 is released and that we upgrade Micronaut support to use it, we can re-integrate the reactive modules.

Should revert https://github.com/micronaut-projects/micronaut-test-resources/pull/188

**Comment by radovanradic** [comment]
@melix Hibernate reactive is supported now, I think changes in #188 can be reverted.

**Comment by radovanradic** [comment]
Right, we missed that in data-hibernate-reactive because there was no test for MySql/Maria. I was able to reproduce it.
Not sure what [this means](https://tinyurl.com/yuzks9cd) really, but looks like MySql is not supported yet in hibernate-reactive 2. Just would expect different error than timeout.
Perhaps can mark these mysql based tests that are failing with `@PendingFeature` and let other dialects build, if makes sense to you.
