### ISSUE TITLE
Introduce a property to disable R2DBC pool

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#399]
### Feature description

Right now, in Micronaut Data we cannot test the configuration without R2DBC pool when it's present on the classpath.

**Comment by melix** [comment]
Can you clarify what you mean? Test resources is agnostic of the R2DBC pool, in the sense it never queries for the pool or anything related.

**Comment by melix** [comment]
But what I mean is that TR doesn't configure anything related to the R2DBC pool. The only thing I see is the classpath inference, which makes it so that if the pool driver is available on classpath, then it's propagated to the test resources service classpath. If you don't want that behavior you have to disable inference in the build script. But it means that if you have to test with and without, then it would have to be in 2 different modules with different test resource services.

**Comment by melix** [comment]
I fail to see how I can do anything. The R2DBC providers are really simple, they don't know about the pool, they don't configure anything, they just return URLs and passwords : https://github.com/micronaut-projects/micronaut-test-resources/blob/5129fe046dbdb06639a6a50a741ea73d71197ba1/test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java#L135

Maybe you could advice?

**Comment by dstepanov** [comment]
The idea would be to skip https://github.com/micronaut-projects/micronaut-test-resources/blob/5129fe046dbdb06639a6a50a741ea73d71197ba1/test-resources-r2dbc/test-resources-r2dbc-pool/src/main/java/io/micronaut/testresources/r2dbc/pool/R2DBCPoolTestResourceProvider.java if there is some property defined, in the same way some of the JDBC resources are skipped https://github.com/micronaut-projects/micronaut-test-resources/blob/5129fe046dbdb06639a6a50a741ea73d71197ba1/test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java

**Comment by melix** [comment]
Oh I see, thanks, I forgot about this provider.
