### ISSUE TITLE
Mysql/Maria JDBC/R2DBC test resources fail to start

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#79]
### Expected Behavior

Some of the JDBC test containers require implicit driver dependency as it's using it to check if the database is running.

https://www.testcontainers.org/modules/databases/mysql/
```
Adding this Testcontainers library JAR will not automatically add a database driver JAR to your project. You should ensure that your project also has a suitable database driver as a dependency.
```
https://github.com/testcontainers/testcontainers-java/blob/master/modules/mysql/build.gradle

My suggestion is to have separate test projects to detect misconfigurations.

### Actual Behaviour

```
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.testcontainers.containers.JdbcDatabaseContainer.getJdbcDriverInstance(JdbcDatabaseContainer.java:200)
	... 83 common frames omitted
```

### Version

3.6.0/1.0.1

**Comment by dstepanov** [comment]
Not sure if it's by design. Documentation does mention a way to add a driver to the test-resources classpath.
My use-case is to use the test resources without the infer classpath.
This helped: 
```
dependencies {
    testResourcesService libs.drivers.jdbc.mysql
}
```

**Comment by alvarosanchez** [comment]
It is intentional, indeed. @melix and I already discussed the possibility to automatically add a driver to the classpath, but ain't an easy task.

**Comment by dstepanov** [comment]
I don't see adding a driver (possibly the latest) to the test resource server as a big problem, it will only be used for the readiness thing.

**Comment by melix** [comment]
It is indeed intentional: it is complicated to figure out what driver to add, whose providing a driver (because db drivers can be added to any jar), and *if* a driver should be added. For example for Oracle there are many implementations to pick from, depending on the JDK version or Oracle db version. Similarly sometimes adding the driver automatically would make the test service startup fail. So I'm -1 on doing this.

**Comment by dstepanov** [comment]
> Similarly sometimes adding the driver automatically would make the test service startup fail.

Not sure what you mean by that. What is going to fail?

I would add one version of the driver that we already have in the BOM.

IMHO not having the driver added will cause more user troubles than having it.

**Comment by alvarosanchez** [comment]
I'd also prefer to add a driver, at least for those cases where we can do that safely.

**Comment by melix** [comment]
> Not sure what you mean by that. What is going to fail?

A typical example is with R2DBC. For MySQL the driver needs to be present on the testcontainers classpath, but not for Oracle. There's no generic logic to figure out what works or not: it's all our knowledge.

> I would add one version of the driver that we already have in the BOM.

This is not really required. IF we wanted to do this, we can simply pass the driver that the user selected to the test resources service classpath. The issue is really to figure out if there's a driver already, and what provides it. To me the logic to do this is not that obvious to get right.
